server:
  port: 9000

eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: server1
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
